{
 "title": "Sustainable Building  Demo Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "bucketInterval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "CarbonIntensity", "query": "${VAR_CARBONINTENSITY}" },
   { "name": "EnergyCost", "query": "${VAR_ENERGYCOST}" }
  ]
 },
 "panels": [
  {
   "title": "Total Electricity Consumption",
   "type": "gauge",
   "description": "Displays electricity consumption for all buildings",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH binned_query AS (\nSELECT bin(time, 1h) as time\n     , avg(ELECTRIC_CURRENT) * avg(VOLTAGE)  AS \"wattHour\"\n     , LOCATION\n  FROM $__database.$__table\n WHERE $__timeFilter\n group by bin(time, 1h), LOCATION\n order by time desc\n)\nSELECT sum (wattHour) as \"PowerUsage\"\n  FROM binned_query",
     "table": "\"power\""
    }
   ]
  },
  {
   "title": "Total GHG (CO2e) Emissions",
   "type": "gauge",
   "description": "Displays total GHG (CO2e) Emissions for all facilities based on electricity consumption in location based calculation methodology.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH binned_query AS (\nSELECT bin(time, 1h) as time\n     , avg(ELECTRIC_CURRENT) * avg(VOLTAGE)  AS \"wattHour\"\n     , LOCATION\n  FROM $__database.$__table\n WHERE $__timeFilter\n group by bin(time, 1h), LOCATION\n order by time desc\n)\nSELECT sum (wattHour) / 1000 * $CarbonIntensity as \"CO2 Emissions\"\n  FROM binned_query",
     "table": "\"power\""
    }
   ]
  },
  {
   "title": "Total Electricity Cost",
   "type": "gauge",
   "description": "Displays total electricity cost for all facilities.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH binned_query AS (\nSELECT bin(time, 1h) as time\n     , avg(ELECTRIC_CURRENT) * avg(VOLTAGE) AS \"wattHour\"\n     , LOCATION\n  FROM $__database.$__table\n WHERE $__timeFilter\n group by bin(time, 1h), LOCATION\n order by time desc\n)\nSELECT sum (wattHour) / 1000 * $EnergyCost as \"Energy Cost\"\n  FROM binned_query",
     "table": "\"power\""
    }
   ]
  },
  {
   "title": "Electricity consumption trend by facility",
   "type": "timeseries",
   "description": "Electricity consumption trend time series data by facility",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH binned_query AS (\nSELECT bin(time, $bucketInterval) as time\n     , avg(ELECTRIC_CURRENT) * avg(VOLTAGE) AS \"AvgPower\"\n     , LOCATION, DeviceName\n  FROM $__database.$__table\n WHERE $__timeFilter\n group by bin(time, $bucketInterval), LOCATION, DeviceName\n order by time desc\n)\nSELECT LOCATION, CREATE_TIME_SERIES(time, PowerByLocation) as \"Electricity Consumption by Facility\"\nFROM (\n  SELECT time, LOCATION, SUM(AvgPower) as \"PowerByLocation\"\n    FROM binned_query\n    GROUP BY time, LOCATION\n   )\nGROUP BY LOCATION",
     "table": "\"power\""
    }
   ]
  },
  {
   "title": "Latest electricity usage by facility",
   "type": "gauge",
   "description": "Displays latest electricity usage by facility",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH latest_records AS (\n  SELECT\n    LOCATION,\n    MAX(time) as latest_time\n  FROM \n    $__database.$__table\n  WHERE\n    $__timeFilter\n  GROUP by\n    LOCATION,\n    DeviceName\n)\n\nSELECT\n  t.ELECTRIC_CURRENT * t.VOLTAGE,\n  t.time,\n  t.LOCATION\nFROM\n  $__database.$__table t\nJOIN\n  latest_records l\nON\n  t.LOCATION = l.LOCATION AND t.time = l.latest_time",
     "table": "\"power\""
    }
   ]
  },
  {
   "title": "CO2 concentration trend by facility",
   "type": "timeseries",
   "description": "CO2 concentration trend time series data by facility",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH binned_query AS (\nSELECT bin(time, $bucketInterval) as time\n     , avg(CO2) AS \"AvgCO2\"\n     , LOCATION\n  FROM $__database.$__table\n WHERE $__timeFilter\n group by bin(time, $bucketInterval), LOCATION\n order by time desc\n)\nSELECT LOCATION, CREATE_TIME_SERIES(time, AvgCO2) as \"Average CO2 ppm\"\n  FROM binned_query\n GROUP BY LOCATION",
     "table": "\"sensor\""
    }
   ]
  },
  {
   "title": "Latest CO2 concentration by facility",
   "type": "gauge",
   "description": "Displays latest CO2 concentration by facility",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH latest_records AS (\n  SELECT\n    LOCATION,\n    MAX(time) as latest_time\n  FROM \n    $__database.$__table\n  WHERE\n    $__timeFilter\n  GROUP by\n    LOCATION\n)\n\nSELECT\n  t.CO2,\n  t.time,\n  t.LOCATION\nFROM\n  $__database.$__table t\nJOIN\n  latest_records l\nON\n  t.LOCATION = l.LOCATION AND t.time = l.latest_time",
     "table": "\"sensor\""
    }
   ]
  },
  {
   "title": "Electricity Consumption by Facilities",
   "type": "stat",
   "description": "Electricity Consumption by Facilities",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH binned_query AS (\nSELECT bin(time, 1h) as time\n     , avg(ELECTRIC_CURRENT) * avg(VOLTAGE) AS \"wattHour\"\n     , LOCATION\n  FROM $__database.$__table\n WHERE $__timeFilter\n group by bin(time, 1h), LOCATION\n order by time desc\n)\nSELECT LOCATION, CREATE_TIME_SERIES(time, wattHour) as \"Facility\"\n  FROM binned_query\n GROUP BY LOCATION",
     "table": "\"power\""
    }
   ]
  },
  {
   "title": "GHG (CO2e) Emissions by Facilities",
   "type": "stat",
   "description": "Displays GHG (CO2e)Emissions by Facilities",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH binned_query AS (\nSELECT bin(time, 1h) as time\n     , avg(ELECTRIC_CURRENT) * avg(VOLTAGE)  AS \"wattHour\"\n     , avg(ELECTRIC_CURRENT) * avg(VOLTAGE) /1000 * $CarbonIntensity as \"CO2Emission\"\n     , LOCATION\n  FROM $__database.$__table\n WHERE $__timeFilter\n group by bin(time, 1h), LOCATION\n order by time desc\n)\nSELECT LOCATION, CREATE_TIME_SERIES(time, CO2Emission) as \"Facility\"\n  FROM binned_query\n GROUP BY LOCATION",
     "table": "\"power\""
    }
   ]
  },
  {
   "title": "Electricity cost by facilities",
   "type": "stat",
   "description": "Electricity cost by facilities",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH binned_query AS (\nSELECT bin(time, 1h) as time\n     , avg(ELECTRIC_CURRENT) * avg(VOLTAGE) AS \"wattHour\"\n     , avg(ELECTRIC_CURRENT) * avg(VOLTAGE) /1000 * $EnergyCost as \"Cost\"\n     , LOCATION\n  FROM $__database.$__table\n WHERE $__timeFilter\n group by bin(time, 1h), LOCATION\n order by time desc\n)\nSELECT LOCATION, CREATE_TIME_SERIES(time, Cost) as \"Facility\"\n  FROM binned_query\n GROUP BY LOCATION",
     "table": "\"power\""
    }
   ]
  },
  {
   "title": "Weather by facility location",
   "type": "geomap",
   "description": "Displays weather info by facility location",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "openweathermap",
     "rawQuery": "WITH latest_records AS (\n  SELECT\n    location,\n    MAX(time) as latest_time\n  FROM \n    $__database.$__table\n  WHERE\n    $__timeFilter\n  GROUP by\n    location\n)\n\nSELECT\n  CASE\n    WHEN t.location = '35.3811-140.0626' THEN 'Chiba'\n    WHEN t.location = '35.3748-139.4311' THEN 'Tokyo'\n    ELSE t.location\n  END as \"City\",\n  -- t.location,\n  t.BAROMETRIC_PRESSURE as \"気圧\",\n  t.STATUS as \"天気\",\n  t.HUMIDITY as \"Humid\",\n  t.TEMP as \"Temp\",\n  t.LON as \"Long\",\n  t.LAT as \"Lat\",\n  t.time as \"Time\"\nFROM\n  $__database.$__table t\nJOIN\n  latest_records l\nON\n  t.location = l.location AND t.time = l.latest_time\nWHERE t.location <> 'chiba'",
     "table": "\"weather\""
    }
   ]
  },
  {
   "title": "Weather by location (Outside)",
   "type": "timeseries",
   "description": "Displays weather data by location which is obtained from Weathermap API",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "openweathermap",
     "rawQuery": "WITH binned_query AS (\nSELECT bin(time, $bucketInterval) as time\n     , avg(TEMP) AS \"AvgTemperature\"\n     , location\n  FROM $__database.$__table\n WHERE $__timeFilter\n group by bin(time, $bucketInterval), location\n order by time desc\n)\nSELECT location, CREATE_TIME_SERIES(time, AvgTemperature) as \"Average Temperature\"\n  FROM binned_query\n  WHERE location <> 'chiba'\n GROUP BY location",
     "table": "\"weather\""
    }
   ]
  },
  {
   "title": "Temperature trend by facility",
   "type": "timeseries",
   "description": "Temperature trend time series data by location (Outside)",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH binned_query AS (\nSELECT bin(time, $bucketInterval) as time\n     , avg(TEMPERATURE) AS AvgTemp\n     , LOCATION\n  FROM $__database.$__table\n WHERE $__timeFilter\n group by bin(time, $bucketInterval), LOCATION\n order by time desc\n)\nSELECT LOCATION, CREATE_TIME_SERIES(time, AvgTemp) as \"Average Temperature\"\n  FROM binned_query\n GROUP BY LOCATION",
     "table": "\"sensor\""
    }
   ]
  },
  {
   "title": "Latest temperature by facilities",
   "type": "bargauge",
   "description": "Displays the latest temperature by facilities",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH latest_records AS (\n  SELECT\n    LOCATION,\n    MAX(time) as latest_time\n  FROM \n    $__database.$__table\n  WHERE\n    $__timeFilter\n  GROUP by\n    LOCATION\n)\n\nSELECT\n  t.TEMPERATURE,\n  t.time,\n  t.LOCATION\nFROM\n  $__database.$__table t\nJOIN\n  latest_records l\nON\n  t.LOCATION = l.LOCATION AND t.time = l.latest_time",
     "table": "\"sensor\""
    }
   ]
  }
 ]
}