{
 "title": "Sustainable Building Demo Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "bucketInterval",
    "label": "集計間隔",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "CarbonIntensity", "query": "${VAR_CARBONINTENSITY}" },
   { "name": "EnergyCost", "query": "${VAR_ENERGYCOST}" }
  ]
 },
 "panels": [
  {
   "title": "合計消費電力量",
   "type": "gauge",
   "description": "全拠点の合計消費電力量を表示します。",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH binned_query AS (\nSELECT bin(time, 1h) as time\n     , avg(ELECTRIC_CURRENT) * avg(VOLTAGE)  AS \"wattHour\"\n     , LOCATION\n  FROM $__database.$__table\n WHERE $__timeFilter\n group by bin(time, 1h), LOCATION\n order by time desc\n)\nSELECT sum (wattHour) as \"PowerUsage\"\n  FROM binned_query",
     "table": "\"power\""
    }
   ]
  },
  {
   "title": "合計GHG (CO2換算) 排出量",
   "type": "gauge",
   "description": "全拠点のエネルギー使用に伴う GHG (CO2換算) 排出量をロケーション基準で算出しています。",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH binned_query AS (\nSELECT bin(time, 1h) as time\n     , avg(ELECTRIC_CURRENT) * avg(VOLTAGE)  AS \"wattHour\"\n     , LOCATION\n  FROM $__database.$__table\n WHERE $__timeFilter\n group by bin(time, 1h), LOCATION\n order by time desc\n)\nSELECT sum (wattHour) / 1000 * $CarbonIntensity as \"CO2 Emissions\"\n  FROM binned_query",
     "table": "\"power\""
    }
   ]
  },
  {
   "title": "合計電力コスト",
   "type": "gauge",
   "description": "全拠点の電力消費に伴う費用を算出しています。",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH binned_query AS (\nSELECT bin(time, 1h) as time\n     , avg(ELECTRIC_CURRENT) * avg(VOLTAGE) AS \"wattHour\"\n     , LOCATION\n  FROM $__database.$__table\n WHERE $__timeFilter\n group by bin(time, 1h), LOCATION\n order by time desc\n)\nSELECT sum (wattHour) / 1000 * $EnergyCost as \"Energy Cost\"\n  FROM binned_query",
     "table": "\"power\""
    }
   ]
  },
  {
   "title": "拠点別の消費電力量トレンド",
   "type": "timeseries",
   "description": "拠点別の消費電力量の時系列データ",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH binned_query AS (\nSELECT bin(time, $bucketInterval) as time\n     , avg(ELECTRIC_CURRENT) * avg(VOLTAGE) AS \"AvgPower\"\n     , LOCATION, DeviceName\n  FROM $__database.$__table\n WHERE $__timeFilter\n group by bin(time, $bucketInterval), LOCATION, DeviceName\n order by LOCATION asc\n)\nSELECT LOCATION, CREATE_TIME_SERIES(time, PowerByLocation) as \"拠点別電力消費量\"\nFROM (\n  SELECT time, LOCATION, SUM(AvgPower) as \"PowerByLocation\"\n    FROM binned_query\n    GROUP BY time, LOCATION\n   )\nGROUP BY LOCATION",
     "table": "\"power\""
    }
   ]
  },
  {
   "title": "拠点別の最新消費電力",
   "type": "gauge",
   "description": "拠点別の最新消費電力を表示",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH latest_records AS (\n  SELECT\n    LOCATION,\n    MAX(time) as latest_time\n  FROM \n    $__database.$__table\n  WHERE\n    $__timeFilter\n  GROUP by\n    LOCATION,\n    DeviceName\n)\n\nSELECT\n  t.ELECTRIC_CURRENT * t.VOLTAGE,\n  t.time,\n  t.LOCATION\nFROM\n  $__database.$__table t\nJOIN\n  latest_records l\nON\n  t.LOCATION = l.LOCATION AND t.time = l.latest_time",
     "table": "\"power\""
    }
   ]
  },
  {
   "title": "拠点別 CO2 濃度トレンド",
   "type": "timeseries",
   "description": "拠点別 CO2 濃度の時系列データ\n[閾値]\n・黄色: 注意\n・赤: 警告",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH binned_query AS (\nSELECT bin(time, $bucketInterval) as time\n     , avg(CO2) AS \"AvgCO2\"\n     , LOCATION\n  FROM $__database.$__table\n WHERE $__timeFilter\n group by bin(time, $bucketInterval), LOCATION\n order by LOCATION asc\n)\nSELECT LOCATION, CREATE_TIME_SERIES(time, AvgCO2) as \"平均 CO2 濃度\"\n  FROM binned_query\n GROUP BY LOCATION",
     "table": "\"sensor\""
    }
   ]
  },
  {
   "title": "拠点別の最新 CO2 濃度",
   "type": "gauge",
   "description": "拠点別の最新の CO2 濃度データ",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH latest_records AS (\n  SELECT\n    LOCATION,\n    MAX(time) as latest_time\n  FROM \n    $__database.$__table\n  WHERE\n    $__timeFilter\n  GROUP by\n    LOCATION\n)\n\nSELECT\n  t.CO2,\n  t.time,\n  t.LOCATION\nFROM\n  $__database.$__table t\nJOIN\n  latest_records l\nON\n  t.LOCATION = l.LOCATION AND t.time = l.latest_time",
     "table": "\"sensor\""
    }
   ]
  },
  {
   "title": "拠点別消費電力量",
   "type": "stat",
   "description": "拠点ごとの消費電力量の内訳",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH binned_query AS (\nSELECT bin(time, 1h) as time\n     , avg(ELECTRIC_CURRENT) * avg(VOLTAGE) AS \"wattHour\"\n     , LOCATION\n  FROM $__database.$__table\n WHERE $__timeFilter\n group by bin(time, 1h), LOCATION\n order by LOCATION asc\n)\nSELECT LOCATION, CREATE_TIME_SERIES(time, wattHour) as \"拠点\"\n  FROM binned_query\n GROUP BY LOCATION",
     "table": "\"power\""
    }
   ]
  },
  {
   "title": "拠点別 GHG (CO2換算) 排出量",
   "type": "stat",
   "description": "拠点別の GHG (CO2換算) 排出量の内訳",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH binned_query AS (\nSELECT bin(time, 1h) as time\n     , avg(ELECTRIC_CURRENT) * avg(VOLTAGE)  AS \"wattHour\"\n     , avg(ELECTRIC_CURRENT) * avg(VOLTAGE) /1000 * $CarbonIntensity as \"CO2Emission\"\n     , LOCATION\n  FROM $__database.$__table\n WHERE $__timeFilter\n group by bin(time, 1h), LOCATION\n order by LOCATION asc\n)\nSELECT LOCATION, CREATE_TIME_SERIES(time, CO2Emission) as \"拠点\"\n  FROM binned_query\n GROUP BY LOCATION",
     "table": "\"power\""
    }
   ]
  },
  {
   "title": "拠点別電力コスト",
   "type": "stat",
   "description": "拠点別の消費電力コスト内訳",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH binned_query AS (\nSELECT bin(time, 1h) as time\n     , avg(ELECTRIC_CURRENT) * avg(VOLTAGE) AS \"wattHour\"\n     , avg(ELECTRIC_CURRENT) * avg(VOLTAGE) /1000 * $EnergyCost as \"Cost\"\n     , LOCATION\n  FROM $__database.$__table\n WHERE $__timeFilter\n group by bin(time, 1h), LOCATION\n order by LOCATION asc\n)\nSELECT LOCATION, CREATE_TIME_SERIES(time, Cost) as \"拠点\"\n  FROM binned_query\n GROUP BY LOCATION",
     "table": "\"power\""
    }
   ]
  },
  {
   "title": "拠点ごとの天気",
   "type": "geomap",
   "description": "拠点ごとの天気情報を表示します",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "openweathermap",
     "rawQuery": "WITH latest_records AS (\n  SELECT\n    location,\n    MAX(time) as latest_time\n  FROM \n    $__database.$__table\n  WHERE\n    $__timeFilter\n  GROUP by\n    location\n)\n\nSELECT\n  CASE\n    WHEN t.location = '35.3811-140.0626' THEN '千葉'\n    WHEN t.location = '35.3748-139.4311' THEN '東京'\n    ELSE t.location\n  END as \"都市\",\n  -- t.location,\n  t.BAROMETRIC_PRESSURE as \"気圧\",\n  t.STATUS as \"天気\",\n  t.HUMIDITY as \"湿度\",\n  t.TEMP as \"気温\",\n  t.LON as \"経度\",\n  t.LAT as \"緯度\",\n  t.time as \"時刻\"\nFROM\n  $__database.$__table t\nJOIN\n  latest_records l\nON\n  t.location = l.location AND t.time = l.latest_time\nWHERE t.location <> 'chiba'",
     "table": "\"weather\""
    }
   ]
  },
  {
   "title": "地域別の天気データ（屋外）",
   "type": "timeseries",
   "description": "Weathermap API経由で取得した地域別天気データ",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "openweathermap",
     "rawQuery": "WITH binned_query AS (\nSELECT bin(time, $bucketInterval) as time\n     , avg(TEMP) AS \"AvgTemperature\"\n     , location\n  FROM $__database.$__table\n WHERE $__timeFilter\n group by bin(time, $bucketInterval), location\n order by location asc\n)\nSELECT location, CREATE_TIME_SERIES(time, AvgTemperature) as \"Average Temperature\"\n  FROM binned_query\n  WHERE location <> 'chiba'\n GROUP BY location",
     "table": "\"weather\""
    }
   ]
  },
  {
   "title": "拠点別の温度トレンド",
   "type": "timeseries",
   "description": "拠点別の温度の時系列データ",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH binned_query AS (\nSELECT bin(time, $bucketInterval) as time\n     , avg(TEMPERATURE) AS AvgTemp\n     , LOCATION\n  FROM $__database.$__table\n WHERE $__timeFilter\n group by bin(time, $bucketInterval), LOCATION\n order by time desc\n)\nSELECT LOCATION, CREATE_TIME_SERIES(time, AvgTemp) as \"平均温度\"\n  FROM binned_query\n GROUP BY LOCATION",
     "table": "\"sensor\""
    }
   ]
  },
  {
   "title": "拠点別の最新の温度",
   "type": "bargauge",
   "description": "拠点別の最新の温度データ",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "database": "\"sustainableBuilding\"",
     "measure": "sustainability_sensor",
     "rawQuery": "WITH latest_records AS (\n  SELECT\n    LOCATION,\n    MAX(time) as latest_time\n  FROM \n    $__database.$__table\n  WHERE\n    $__timeFilter\n  GROUP by\n    LOCATION\n)\n\nSELECT\n  t.TEMPERATURE,\n  t.time,\n  t.LOCATION\nFROM\n  $__database.$__table t\nJOIN\n  latest_records l\nON\n  t.LOCATION = l.LOCATION AND t.time = l.latest_time",
     "table": "\"sensor\""
    }
   ]
  }
 ]
}